version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  frontend:
    working_directory: ~/app/udagram/udagram-frontend
    executor: node/default
     # deploy step will run only after manual approval
    steps: 
      - checkout:
          path: ~/app # checkout code
      - node/install: # install node
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-frontend
      - run: # Build Frontend
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-region: AWS_REGION
          profile-name: AWS_PROFILE
     
      - run: # Deploy Frontend
          name: Deploy Frontend
          command: aws s3 cp --recursive  ./www s3://udagram/
  
  server:
    working_directory: ~/app/udagram/udagram-api
    executor: node/default
     # deploy step will run only after manual approval
    steps:
      - checkout: # checkout code
          path: ~/app
      - node/install-packages: # install node
          app-dir: ~/app/udagram/udagram-api
      - aws-cli/install
      - eb/setup
      - run: # Deploy server
          name: Deploy Server
          command: npm run deploy
workflows:
  build_and_deploy: # the job to conditionally run based on the filter by main/master
    jobs:
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
      - frontend:
          filters:
            branches:
              only:
                - master
      - server:
          filters:
            branches:
              only:
                - master
